---
- name: Installation of Apache 
  hosts: web 
  become: true  # activer l'escalage de privilèges
  tasks: 
    - name: Install apache
      ansible.builtin.apt:
          name: apache2
          state: latest 
          update_cache: true 
    - name: Start apache
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: true
    - name: Create index.html with a welcome message
      copy:
        dest: /var/www/html
        content: "Welcome to my Ansible-built Apache server!"
        owner: root
        group: root
        mode: '0644'
      

